### ISSUE TITLE
t/parse.t test failures

### ISSUE THREAD

**Issue by eserte** [jmacdotorg/microformats2-perl#1]
On some systems t/parse.t fails. See http://matrix.cpantesters.org/?dist=Web-Microformats2+0.3 for an overview of test reports. I don't see a pattern for these failures, nor is statistical analysis helpful to find a reason.

**Comment by jmacdotorg** [comment]
Oh wow! Thanks for pointing this out.

That does look quite uneven to the eye! I suppose the best way to start would be to try testing on one of the systems that shows up reddest in this chart, e.g. Perl 5.1X.X on Linux.
